import_smartcampus() ::= <<
<!-- Jquery librairies -->
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<!-- D3.js librairies -->
<script type="text/javascript" src="http://mbostock.github.com/d3/d3.js"></script>
<!-- HeatMap.js librairies -->
<script type="text/javascript" src="http://smartcampus.github.io/plan-visualizer/heatmap.js"></script>
<!-- Javascript file -->
<script type="text/javascript" src="http://ilogre.github.io/plan-visualizer/handling-svg-biblio.js"></script>
<!-- CSS file -->
<link rel="stylesheet" href="http://smartcampus.github.io/plan-visualizer/handling-svg-biblio.css">
>>